In [ ]:
# Statistical analysis
# Calculate the eigenvalues and eigenvectors of a large sparse matrix using numpy's sparse matrix handling.


In [4]:
import numpy as np
from scipy.sparse import random
from scipy.sparse.linalg import eigsh

size = 1000
density = 0.05 
sparse_matrix = random(size, size, density=density, format='csr')


sparse_matrix = sparse_matrix + sparse_matrix
k = 6 
eigenvalues, eigenvectors = eigsh(sparse_matrix, k=k, which='LM')

print("Eigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)


Eigenvalues:
 [-15.92118059 -15.72318327  15.73077983  15.79573078  15.90140857
  51.57041124]

Eigenvectors:
 [[ 0.04950514 -0.02800299 -0.00376952  0.02799062  0.00833986 -0.02468794]
 [ 0.00509569 -0.03324115  0.03374979 -0.00379727 -0.02119024 -0.034151  ]
 [-0.04326352  0.0018934  -0.00346228 -0.01916164 -0.04265358 -0.02535221]
 ...
 [ 0.05674367 -0.03851369  0.02855227  0.06720561 -0.00020648 -0.02896864]
 [ 0.01923164 -0.03511447 -0.04852572 -0.01152286 -0.00304417 -0.02742376]
 [-0.01069292 -0.03447048  0.07527595 -0.02152093 -0.01246723 -0.03827673]]
